security:
  providers:
    user_actor:
      id: security.user_provider.user_actor
  firewalls:
    api_register:
      pattern: "^/api/auth/register"
      anonymous: ~
    api:
      pattern: "^/api/*"
      stateless: true
      json_login:
        check_path: /api/auth/login
        username_path: email
        success_handler:          lexik_jwt_authentication.handler.authentication_success
        failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        require_previous_session: false
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
      logout:
        path: "/api/auth/logout"
  encoders:
    Mleko\LetsPlay\Security\UserActor:
      algorithm:            bcrypt
      cost:                 10
